export const COLLECTIONS = {
  cardAccounts: "cardAccounts",
  monthlyCardPayments: "monthlyCardPayments",
  monthlyIncomePaydays: "monthlyIncomePaydays",
  paydayMode: "paydayMode",
  houseBills: "houseBills",
  incomeItems: "incomeItems",
  savingsGoals: "savingsGoals",
  shoppingItems: "shoppingItems",
  myBills: "myBills",
  monthlyAdjustments: "monthlyAdjustments",
  loanedOutItems: "loanedOutItems",
  bankBalances: "bankBalances",
  purchasePlans: "purchasePlans",
  monthSnapshots: "monthSnapshots",
  ledgerEntries: "ledgerEntries",
  recurrenceRules: "recurrenceRules",
  monthClosures: "monthClosures",
  reconciliations: "reconciliations",
  imports: "imports",
  pushSubscriptions: "pushSubscriptions",
  alertSettings: "alertSettings",
  alertStates: "alertStates",
  backups: "backups",
  commands: "commands",
  auditEvents: "auditEvents",
  auditEventsArchive: "auditEventsArchive"
} as const;

export type CollectionKey = keyof typeof COLLECTIONS;
